export const categoryMappings: { [key: string]: RegExp } = {
  'Fries': /(fries|ore-ida)/i,
  'Potatoes': /(idahoan)/i,
  'Pasta': /(pasta|spaghetti|ziti|penne|rotini|linguine|fettuccine|lasagna|macaroni|rigatoni|tortelloni|tortellini|de?.cecco|barilla?.medium?.shells|cavatappi|hannaford?.small?.shells|ditalini|hakubaku|barilla?.campanelle|barilla?.protein|potato?.gnocchi|rice?.noodles)/i,
  'Energy Drinks': /(red?.bull|celsius)/i,
  'LU Ecolier': /(lu.?ecolier|lu.?petit|petit.?ecolier)/i,
  'Rice': /(brown?.rice|jasmine?.rice|carolina|rice?.pilaf|quinoa|riceselect|basmati|microwave.*cuban|royal.*microwave)/i,
  'Vinegar': /vinegar/i,
  'Beer/Cider': /(beer|corona|pilsner|downeast?.unfiltered|stella?.artois|paradox|frog?.ally|frog?.alley)/i,
  'Beef Jerky': /(beef?.jerky)/i,
  'Ground Beef': /(ground?.beef|beef?.pastries|beef?.patties)/i,
  'Hot Dogs': /(beef?.franks|hot?.dogs|beef?.frnks)/i,
  'Roast Beef': /(roast?.beef|rst?.bf)/i,
  'Turkey': /(turkey|trk?.br)/i,
  'Ham': /(ham\b)/i,
  'Hot Wings': /(hot?.wng|hot?.wing|chkn?.hot)/i,
  'Chicken': /(chicken?.breast|chicken?.tenders|grilled?.chicken|rotisserie?.chicken|applewood?.smoked?.chicken|Rotisserie|crispy?.sesame?.chicken|chicken?.nuggets|chkn|chicken?.tendr|ground?.chicken)/i,
  'Hand Soap': /(hand.?soap|sft?.soap)/i,
  'Frozen Pizza': /(screamin|frozen.*pizza|pizza.*frozen|pizza?.kitchen)/i,
  'Pepperoni/Sausage': /(pepperoni|salame|veroni|salami|fratelli?.beretta|busseto)/i,
  'Chocolate Chips': /(baking?.chips|dark?.chocolate?.chips|sweet?.chocolate?.chips|morsel)/i,
  'Couscous': /pearl?.couscous/i,
  'Baking (flour, sugar,...)': /(flour|all.?purpose|domino|baking?.soda|carnation|betty?.crocker|brownie?.mix|baking?.bar|vanilla?.extract|puff?.pastry|cocoa?.powder|honey\b|honey?.farm|bread?.crumbs|panko|corn?.syrup|pure?.pumpkin|corn?.starch|pie?.crust|baking?.powder|powdered?.sugar|stuffing)/i,
  'Donuts': /(donut|doughnut)/i,
  'Ice Cream': /(ice.?cream|gelato|mickey?.bars|th?.orignal|vanilla?.ic|drumstick|chocolate?.cone|tillamook|cky?.cream?.ic)/i,
  'Bacon': /bacon/i,
  'Crescents': /(crescent?.rolls)/i,
  'Butter': /(butter|margarine)/i,
  'Paper towels': /paper.?towels?/i,
  'Bread': /(white.?bread|sandwich.?bread|pita?.bread|baguette|parisien?.french?.bread|flatbread|english?.muffins|bagel|parisien|french?.loaf|pills|dinner?.rolls|crst?.rolls)/i,
  'Deodorant': /(deodorant|antiperspirant)/i,
  'Other Personal': /(always?.ultra|cotton?.swabs|lip?.balm|liquid?.mask|scunci|claw?.clip|shave?.gel|gillette|hand?.warmer)/i,
  'Chocolate Candies': /(chocolate?.bar|lindt|hugs?.white?.creme|kinder|dove?.promises|chocolate?.candies|ferrero?.rocher|ferrero?.milk?.chocolate|chocolate?.candy|dark?.chocolate\b|m&m\b|m&m's|crunch?.buncha|buncha?.crunch|gum\b)/i,
  'Coffee': /(coffee|espresso|k-cup)/i,
  'Oil': /(olive?.oil|oil?.cooking?.spray|pam?.regular|canola?.oil)/i,
  'Homemade Pizza': /(pizza.?dough|pizza?.sauce|galbani|italian?.sausage|ground?.chorizo|hannaford?.hot?.italian|grnd?.ssg|itln?.grnd)/i,
  'Salmon': /(salmon)/i,
  'Goldfish': /(goldfish)/i,
  'Whipped Creme': /(whipped?.creme)/i,
  'Trash Bags': /(tall?.kitchen|leaf?.bags|trash?.bags|gallon?.bags)/i,
  'Cereal Bars': /(made?.good|granola?.bars|clif?.kid|love?.crunch|krispie?.treats|protein?.bar|protein?.bars|kind?.bar)/i,
  'Cookies': /(chocolate?.chip?.cookies|oreo|sugar?.cookies|chocolate?.cookies|pepperidge?.farm|perrotta|cookie?.bites|back?.to?.nature?.classic?.creme|cookie|cookies)/i,
  'Grated Cheese & Parmesan': /(cabot?.shredded|kraft?.grated?.parmesan|cheddar?.shredded?.cheese|kraft?.finely?.shredded|mexican?.shredded|shredded.*cheese|cheese.*shredded|shredded.*parmesan|grated.*parmesan|shredded)/i,
  'Ramen': /(ramen)/i,
  'Eggs': /eggs/i,
  'Milk & Chocolate Milk': /(stonyfield?.organic?.whole?.milk|horizon?.organic|hot?.cocoa?.mix|coconut?.milk|rebbl?.organic|horizon|hrizon|almondmilk|hot?.cocoa)/i,
  'Shampoo & Conditioner': /(conditioner|pantene|shampoo)/i,
  'Body Wash': /(clean?.body?.wash|gel?.wash|body?.wash)/i,
  'Spices/Sauces': /(hot?.ones|taco?.seasoning?.mix|cholula?.chipotle|enchilada?.sauce|soy?.sauce|pesto?.sauce|dip|mccormick|delallo?.olive?.tapenade|red?.curry?.paste|homemade?.alfredo|promise?.organic?.basil|mayonnaise|alfredo?.sauce|black?.peppercorn|dressing|vinaigrette|pad?.thai|cranberry?.sauce|liq?.basil|teriyaki|ranch|green?.chiles|lemon?.juice|bouillon|gravy|peprcrn|grndr)/i,
  'Wipes': /(pampers|lysol|clorox|baby?.wipes|wps|wipes)/i,
  'Naan': /naan/i,
  'Marshmallows': /(marshmallows|jet?.puff)/i,
  'Clothes Washing': /(tide|bounce)/i,
  'Chips': /(pringles|tortilla?.chips|takis|bbq?.chips|frito?.lay|style?.salsa|sea?.salt?.chips|original?.guacamole|potato?.chips|kettle?.cooked)/i,
  'Homemade Sushi': /(sushi?.grain?.rice|seaweed?.sheets)/i,
  'Toilet Paper': /(scott?.bath?.tissue|toilet?.paper)/i,
  'Medecin/Vitamins': /(vicks?.dayQuil|nature?.made|hydration?.multiplier|flintstones?.gummies|one?.a?.day|zyrtec|advil|probiotic|hyland|lotrimin|prime?.blue|cooling?.gel|vaseline|congestion?.nasal|icy?.hot|mucinex|zzzquil|alka-seltzer|bactine)/i,
  'Ground Turkey': /ground?.turkey/i,
  'Salt': /(morton|kosher?.salt|salt)/i,
  'Tofu': /tofu/i,
  'Pudding': /(pudding|kozy?.shack|chocolate?.mousse)/i,
  'Yogurt': /(chobani|yogurt)/i,
  'Cake': /(yule?.log|chocolate?.cake|panettone|truffle?.bomb|cheesecake|cake|pie\b)/i,
  'Steak': /(sirloin|ribeye|London?.Broil|top?.round?.steak|steak|bison|beef?.bottom|stewing?.beef)/i,
  'Vegetables': /(asparagus|avocado|brocolli|potatoes|carrot|green?.beans|baby?.spinach|onions|squash|garlic|broccoli|cluster?.tomatoes|cucumber|basil?.leaves|living?.basil|pepper?.strips|black?.olives|sweet?.peppers|chestnuts|bombs?.tomatoes|grape?.tomatoes|bella?.mushrooms|petite?.peas|limes|edamame|tomatoes|tomato|microgreens|sprouts|corn|sweet?.pepper|celery|leek|onion|jalapeno)/i,
  'Fruits': /(berry?.platter|blueberries|strawberries|blackberries|kiwi?.fruit|plums|pineapple|bananas|mixed?.berries|pumpkins|grapes|mandarin?.bag|seedless?.watermelon|raspberries|mandarin|watermelon|apple|lemon|mango|fruit)/i,
  'Whole Cheese': /(cracker barrel|boursin|brie?.cheese|cabot?.simply?.sharp|jarlsberg?.cheese|muenster?.cheese|belGioioso|blue?.cheese|camembert|gouda?.wedge|coeur?.de?.brie|cheese?.curds|cream?.cheese|fondue|chs?.crd|jarlsberg)/i,
  'Beans': /(goya.*beans|pigeon?.peas|beans|chickpeas|garbanzos)/i,
  'Spray Cleaners': /(scrubbing?.bubbles|windex|granite?.gold|weiman)/i,
  'Nutella Crackers': /(go?.hazelnut?.spread|nutella?.&?.go)/i,
  'Nutella': /nutella/i,
  'Foil & Parchment': /(foil|parchment)/i,
  'Dishwashing': /(dishwashing|jet?.dry|cascade?.platinum|cascade|dawn)/i,
  'Other Drinks': /(orange?.juice|capri?.sun|kombucha|lime?.soda|poland?.spring|sparkling?.tonic|grape?.juice|polar?.seltzer|electrolyte|liquid?.i\.?v\.|san?.pel|pellegrino|iced?.tea|coconut?.water|distilled?.water)/i,
  'Other Snacks': /(pop-tarts|uncrustables|kelloggs?.graham|jell-o|mixed?.nuts|sambazon|little?.debbie|snack?.mix|two-bite|snack?.packs|goldbears|triscuit|pecan?.halves|honey?.biscuits|mallomars?.pure?.chocolate|krispies?.treats|pine?.nuts|beef?.stick|hostess|pretzel?.sticks|muddy?.bites|petit?.fours|collection?.hershey|mush?.minis|mush?.dbl|mush?.double|pistachio|wheat?.thins|crackers|swiss?.roll|muffin|little?.bites|sqshmllw|seaweed?.snacks|rice?.crisps|harvest?.snaps|milk?.straws|pocky)/i,
  'Pork': /(all?.natural?.pork|boneless?.pork|hatfield|pork?.dumplings|center?.cut?.pork|pork?.bao)/i,
  'Cereal': /(chex?.cereal|tasteeos?.cereal|wheat?.cereal|cereal|rolled?.oats)/i,
  'Tissues': /(kleenex|puffs)/i,
  'Other Cleaning Products': /(liquid-plumr|spinbrush|tape|windshield|drain?.clog|sponges|ant?.bait|swiffer|mopping?.pad)/i,
  'Ziploc': /ziploc/i,
  'Dental': /(toothpaste|flossers|oral-b|toothbrush|clgt|mint?.tp)/i,
  'Pilmeni': /(catelli?.meatball)/i,
  'Samosa': /sukhi/i,
  'Frozen Meals': /(innovasian|potstickers|jimmy?.dean|biscuit?.sandwich|p\.?f\.?.chang|evol|jackfruit)/i,
  'Hair Gel': /fructis/i,
  'Chapstick': /chapstick/i,
  'BBQ': /kingsford/i,
  'Stock & Broth': /(stock|broth|bouillon?.cubes)/i,
  'Starkist': /starkist/i,
  'Whipping Cream/Heavy Cream': /(whipping?.cream|whipped?.cream|heavy?.cream)/i,
  'Sour Cream': /(sour?.cream)/i,
  'Tacos & Tortillas': /(mission?.restaurant|taco?.dinner|tortilla|wrap)/i,
  'Tomato Sauce': /hunt/i,
  'Hair Color': /hair?.color/i,
  'Salad': /(salad?.kit|spring?.mix|little?.leaf)/i,
  'Panera Mac and Cheese': /panera/i,
  'Ice Melt': /(roadrunner|rdrnnr|ice.?mlt)/i,
  'Plates/Cups': /(clear?.cups)/i,
  'Flowers': /(cut?.flowers|bqt|bouquet)/i,
  'Office Supplies': /(printer?.paper|multipurpose?.paper|index?.cards)/i,
  'Bags & Fees': /(bag?.rtg|bag?.med|bag?.fee)/i,
  'Gift Cards': /(roblox|fornite|fortnite)/i,
};
