export const categoryMappings: { [key: string]: RegExp } = {
  'Fries': /(fries|ore-ida)/i,
  'Potatoes': /(idahoan)/i,
  'Pasta': /(pasta|spaghetti|ziti|penne|rotini|linguine|fettuccine|lasagna|macaroni|rigatoni|tortelloni|tortellini|de?.cecco|barilla?.medium?.shells|cavatappi|hannaford?.small?.shells|ditalini|hakubaku|barilla?.campanelle)/i,
  'Red Bull': /red bull/i,
  'LU Ecolier': /(lu.?ecolier|lu?.petite)/i,
  'Rice': /(brown?.rice|jasmine?.rice|carolina|rice?.pilaf|sushi?.grain?.rice)/i,
  'Vinegar': /vinegar/i,
  'Beer/Cider': /(beer|corona|pilsner|downeast?.unfiltered|stella?.artois)/i,
  'Ground Beef': /(ground?.beef)/i,
  'Hot Dogs': /(beef?.franks|hot?.dogs)/i,
  'Chicken': /(chicken?.breast|chicken?.tenders|grilled?.chicken|rotisserie?.chicken|applewood?.smoked?.chicken|Rotisserie|crispy?.sesame?.chicken|chicken?.nuggets)/i,
  'Hand Soap': /hand.?soap/i,
  'Frozen Pizza': /Screamin/i,
  'Pepperoni/Sausage': /(pepperoni|salame|veroni)/i,
  'Chocolate Chips': /(baking?.chips|dark?.chocolate?.chips|sweet?.chocolate?.chips)/i,
  'Couscous': /pearl?.couscous/i,
  'Baking (flour, sugar,...)': /(flour|all.?purpose|domino|baking?.soda|carnation|betty?.crocker|brownie?.mix|baking?.bar|vanilla?.extract)/i,
  'Donuts': /(donut|doughnut)/i,
  'Ice Cream': /(ice.?cream|gelato|mickey?.bars)/i,
  'Bacon': /bacon/i,
  'Crescents': /(crescent?.rolls)/i,
  'Butter': /(butter|margarine)/i,
  'Paper towels': /paper.?towels?/i,
  'Bread': /(white.?bread|sandwich.?bread|pita?.bread|baguette|parisien?.french?.bread|flatbread)/i,
  'Deodorant': /(deodorant|antiperspirant)/i,
  'Other Personal': /(always?.ultra|cotton?.swabs|lip?.balm|liquid?.mask)/i,
  'Chocolate Candies': /(chocolate?.bar|lindt|hugs?.white?.creme|kinder|dove?.promises|chocolate?.candies|ferrero?.rocher|ferrero?.milk?.chocolate)/i,
  'Coffee': /(coffee|espresso|k-cup)/i,
  'Oil': /(olive?.oil|oil?.cooking?.spray|pam?.regular|canola?.oil)/i,
  'Homemade Pizza': /(pizza.?dough|pizza?.sauce|galbani|italian?.sausage|ground?.chorizo|hannaford?.hot?.italian)/i,
  'Salmon': /(salmon)/i,
  'Goldfish': /(goldfish)/i,
  'Whipped Creme': /(whipped?.creme)/i,
  'Trash Bags': /(tall?.kitchen|leaf?.bags|trash?.bags|gallon?.bags)/i,
  'Cereal Bars': /(made?.good|granola?.bars|clif?.kid|love?.crunch|krispie?.treats)/i,
  'Cookies': /(chocolate?.chip?.cookies|oreo|sugar?.cookies|chocolate?.cookies|pepperidge?.farm|perrotta|cookie?.bites|back?.to?.nature?.classic?.creme)/i,
  'Grated Cheese & Parmesan': /(cabot?.shredded|kraft?.grated?.parmesan|cheddar?.shredded?.cheese|kraft?.finely?.shredded|mexican?.shredded)/i,
  'Ramen': /ramen?.noodles/i,
  'Eggs': /eggs/i,
  'Milk & Chocolate Milk': /(stonyfield?.organic?.whole?.milk|horizon?.organic|hot?.cocoa?.mix)/i,
  'Shampoo & Conditioner': /(conditioner|pantene|shampoo)/i,
  'Body Wash': /(clean?.body?.wash|gel?.wash)/i,
  'Spices/Sauces': /(hot?.ones|taco?.seasoning?.mix|cholula?.chipotle|enchilada?.sauce|soy?.sauce|pesto?.sauce|dip|mccormick|delallo?.olive?.tapenade|red?.curry?.paste|homemade?.alfredo|promise?.organic?.basil|mayonnaise)/i,
  'Wipes': /(pampers|lysol|clorox|baby?.wipes)/i,
  'Naan': /naan/i,
  'Marshmallows': /marshmallows/i,
  'Clothes Washing': /(tide?.pods|tide?.power|bounce)/i,
  'Chips': /(pringles|tortilla?.chips|takis|bbq?.chips|frito?.lay)/i,
  'Toilet Paper': /scott?.bath?.tissue/i,
  'Medecin/Vitamins': /(vicks?.dayQuil|nature?.made|hydration?.multiplier|flintstones?.gummies|one?.a?.day|zyrtec|advil|probiotic|hyland|lotrimin|prime?.blue|cooling?.gel|vaseline)/i,
  'Ground Turkey': /ground?.turkey/i,
  'Salt': /morton/i,
  'Tofu': /tofu/i,
  'Pudding': /(pudding|kozy?.shack|chocolate?.mousse)/i,
  'Yogurt': /(chobani)/i,
  'Cake': /(yule?.log|chocolate?.cake|panettone)/i,
  'Steak': /(sirloin|ribeye|London?.Broil|top?.round?.steak|steak|bison|beef?.bottom|stewing?.beef)/i,
  'Vegetables': /(asparagus|avocado|brocolli|potatoes|carrot|green?.beans|baby?.spinach|onions|squash|garlic|broccoli|cluster?.tomatoes|cucumber|basil?.leaves|living?.basil|pepper?.strips|black?.olives|sweet?.peppers|chestnuts|bombs?.tomatoes|grape?.tomatoes|bella?.mushrooms|petite?.peas|limes|edamame)/i,
  'Fruits': /(berry?.platter|blueberries|strawberries|blackberries|kiwi?.fruit|plums|pineapple|bananas|mixed?.berries|pumpkins|grapes|mandarin?.bag|seedless?.watermelon)/i,
  'Whole Cheese': /(cracker barrel|boursin|brie?.cheese|cabot?.simply?.sharp|jarlsberg?.cheese|muenster?.cheese|belGioioso|blue?.cheese|camembert|gouda?.wedge|coeur?.de?.brie|cheese?.curds|cream?.cheese|fondue)/i,
  'Beans': /(goya.*beans|pigeon?.peas)/i,
  'Spray Cleaners': /(scrubbing?.bubbles|windex|granite?.gold|weiman)/i,
  'Nutella Crackers': /(go?.hazelnut?.spread|nutella?.&?.go)/i,
  'Nutella': /nutella/i,
  'Foil & Parchment': /(foil|parchment)/i,
  'Dishwashing': /(dishwashing|jet?.dry|cascade?.platinum)/i,
  'Other Drinks': /(orange?.juice|capri?.sun|kombucha|lime?.soda|poland?.spring|sparkling?.tonic|grape?.juice)/i,
  'Other Snacks': /(pop-tarts|uncrustables|kelloggs?.graham|jell-o|mixed?.nuts|sambazon|little?.debbie|snack?.mix|two-bite|snack?.packs|goldbears|triscuit|pecan?.halves|honey?.biscuits|mallomars?.pure?.chocolate|krispies?.treats|pine?.nuts|beef?.stick|hostess)/i,
  'Pork': /(all?.natural?.pork|boneless?.pork|hatfield|pork?.dumplings|center?.cut?.pork)/i,
  'Cereal': /(chex?.cereal|tasteeos?.cereal|wheat?.cereal)/i,
  'Tissues': /(kleenex|puffs)/i,
  'Other Cleaning Products': /(liquid-plumr|spinbrush|tape|windshield|drain?.clog|sponges)/i,
  'Ziploc': /ziploc/i,
  'Dental': /(toothpaste|flossers|oral-b|toothbrush)/i,
  'Pilmeni': /(catelli?.meatball|bouillon?.cubes)/i,
  'Samosa': /sukhi/i,
  'Hair Gel': /fructis/i,
  'Chapstick': /chapstick/i,
  'BBQ': /kingsford/i,
  'Stock & Broth': /(stock|broth)/i,
  'Starkist': /starkist/i,
  'Whipping Cream/Heavy Cream': /(whipping?.cream|whipped?.cream|heavy?.cream)/i,
  'Sour Cream': /(sour?.cream)/i,
  'Tacos & Tortillas': /(mission?.restaurant|taco?.dinner)/i,
  'Tomato Sauce': /hunt/i,
  'Hair Color': /hair?.color/i,
  'Salad': /salad?.kit/i,
  'Panera Mac and Cheese': /panera/i,
  'Ice Melt': /(roadrunner)/i,
  'Plates/Cups': /(clear?.cups)/i,
  'Flowers': /(cut?.flowers)/i,
};
